name: Deploy to cPanel

on:
  push:
    branches:
      - production

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository code
      - name: Checkout Code
        uses: actions/checkout@v3

      # Upload files to cPanel using FTP
      - name: Deploy via FTP
        uses: SamKirkland/FTP-Deploy-Action@v4
        with:
          server: ftp://your-cpanel-server.com
          username: ${{ secrets.CPANEL_USERNAME }}
          password: ${{ secrets.CPANEL_PASSWORD }}
          local-dir: ./ # Specify the directory to deploy
          server-dir: /public_html # Specify your destination directory on cPanel
          exclude: |
            .git*
            node_modules/*
            *.yml
            *.md

